pipeline {
    agent any
    stages {
        stage('Set AWS Credentials') {
            steps {
                sh 'cp /home/ubuntu/variables.tf ./app-server-terraform/'
                echo 'AWS credentials set.'                
            }
        }
        stage('Build Infra App') {
            steps {
                sh 'cd app-server-terraform && sudo -S terraform init && sudo -S terraform plan -lock=false && sudo -S terraform apply -auto-approve -lock=false '
                echo 'App infra built'             
            }
        }
    }
}
