pipeline {
    agent any
    stages {
        stage('Set AWS Credentials') {
            steps {
                sh 'cp /home/ubuntu/variables.tf ./app-server-terraform/'
                echo 'AWS credentials set.'                
            }
        }
        stage('Build Infra App') {
            steps {
                sh 'cd app-server-terraform && terraform init && terraform plan && terraform apply -auto-approve '
                echo 'App infra built'             
            }
        }
    }
}
