pipeline {
    agent any
    stages {
        stage('Set AWS Credentials') {
            steps {
                sh 'cp /local/bsafe/variables.tf ./app-server-terraform/'
                echo 'AWS credentials set.'                
            }
        }
        stage('Build Infra App') {
            steps {
                sh 'cd app-server-terraform && terraform init && terraform plan -lock=false && terraform apply -auto-approve -lock=false '
                echo 'App infra built'             
            }
        }
    }
}
